# -*- coding: utf-8 -*-
"""semantic_struct.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/151MeA7f6WRyIkRMMn20Rj2HLRIu_Ouum
"""

!pip install -U tokenizers transformers accelerate bitsandbytes

!git clone https://github.com/apache/tika.git && cd tika && git checkout b6bcce634

"""**0. Import requireed modules**"""

import numpy as np
import torch
from transformers import AutoTokenizer, AutoModel
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.cluster import AgglomerativeClustering
from pathlib import Path
import csv
# ...

"""**1. Provide the path of java files and load their source code into a list**"""

SOURCE_CODE_DIR = Path("/content/tika/tika-core/src/main/java")
OUTPUT_DIR = Path("/content/output")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

from google.colab import drive
drive.mount('/content/drive')

# focused_rsf_path = Path("/content/drive/MyDrive/dsse_arcade_outputs/tika-focused.rsf")
# classes_set = set()
# with open(focused_rsf_path, mode="r") as f:
#   for line in f:
#     rsf_contents = line.split(" ")
#     classes_set.update(rsf_contents[1:])
# cleaned_class_list = []
# class_list = list(classes_set)
# cleaned_class_list = [line.strip() for line in class_list if line.strip()]
# cleaned_class_list = list(set(cleaned_class_list))
# cleaned_class_list.sort()

# files_list = []
# # .rglob() searches the root folder and all sub-folders automatically
# for file_path in SOURCE_CODE_DIR.rglob('*.java'):
#     if file_path.is_file():
#         with open(file_path, 'r', encoding='utf-8') as f:
#             files_list.append(f.read())

cleaned_class_list = []

for file_path in SOURCE_CODE_DIR.rglob('*.java'):
    path_str = str(file_path.as_posix()) # Ensure forward slashes

    if file_path.is_file() and ("org/apache/tika/detect" in path_str or "org/apache/tika/parser" in path_str):
        relative_path = path_str.split("src/main/java/")[1]

        class_name = relative_path.replace("/", ".").replace(".java", "")
        cleaned_class_list.append(class_name)

cleaned_class_list.sort()

len(cleaned_class_list)

cleaned_class_list

with open(Path("/content/class_index.csv"), "w", newline="", encoding="utf-8") as file:
    writer = csv.writer(file)
    writer.writerow(["Index", "Class Name"])
    for index, class_name in enumerate(cleaned_class_list):
        writer.writerow([index, class_name])

def path_rewriter(java_class):
  class_path = Path(f"/content/tika/tika-core/src/main/java/{java_class.replace(".","/")}.java")
  return class_path

class_filepath = [path_rewriter(class_path) for class_path in cleaned_class_list]
# print(type(class_filepath[0]))
# print(class_filepath[0])
# len(class_filepath)

# files_list = []
# # .rglob() searches the root folder and all sub-folders automatically
# for file_path in SOURCE_CODE_DIR.rglob('*.java'):
#     if file_path.is_file():
#         with open(file_path, 'r', encoding='utf-8') as f:
#             files_list.append(f.read())



# Using alternative list
files_list = []
# .rglob() searches the root folder and all sub-folders automatically
for file_path in class_filepath:
    if file_path.is_file():
        with open(file_path, 'r', encoding='utf-8') as f:
            files_list.append(f.read())
    else:
      print(f"File {file_path} not found")
      files_list.append("")

len(files_list)

#SANITY CHECK
print(f"File 0 length: {len(files_list[0])} characters")
print(f"File 1 length: {len(files_list[1])} characters")
print(f"File 20 length: {len(files_list[20])} characters")

if files_list[0] == files_list[1]:
    print("CRITICAL BUG: The files are identical. Check the file reading loop.")
else:
    print("Files are unique. The bug is in the embedding model math.")



from google.colab import drive
drive.mount('/content/drive')

"""**2. Retrieve the Hugging Face token securely from Colab's "Secrets" tab (the key icon on the left).**"""

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from google.colab import userdata

try:
    hf_token = userdata.get('HF_TOKEN')
except userdata.SecretNotFoundError:
    print("WARNING: 'HF_TOKEN' not found in Colab Secrets.")
    hf_token = None

"""**3. Hardware optimization (Quantization)**"""

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True, # What is loaded in 4 bit? why?
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4"
)

"""**4. Generate embeddings**"""

embedding_model_name = "nomic-ai/nomic-embed-code"

tokenizer = AutoTokenizer.from_pretrained(embedding_model_name,token=hf_token)
model = AutoModel.from_pretrained(embedding_model_name,token=hf_token,quantization_config=bnb_config)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

"""**5. Construct the semantic similarity matrix**"""

def last_token_pooling(hidden_states, attention_mask):
    sequence_lengths = attention_mask.sum(-1) - 1
    return hidden_states[torch.arange(hidden_states.shape[0]), sequence_lengths]

def embed_source_code(code_files):
    embeddings = []
    for i, code in enumerate(code_files):
        # Max length 512 (for current model and available memory size)
        inputs = tokenizer(code, padding=True, truncation=True, max_length=512, return_tensors="pt").to(device)

        with torch.no_grad():
            outputs = model(**inputs)
            model_output = outputs.last_hidden_state
            vector = last_token_pooling(model_output, inputs['attention_mask'])
            vector = vector.squeeze(0).cpu().numpy()

        embeddings.append(vector)
    return np.vstack(embeddings)

embeddings = embed_source_code(files_list)
semantic_matrix = cosine_similarity(embeddings)

print(embeddings.shape)
print(semantic_matrix.shape)

tokenizer.padding_side

np.save(Path('/content/drive/MyDrive/embeddings.npy'), embeddings)
np.save(Path('/content/drive/MyDrive/semantic_matrix.npy'), semantic_matrix)

semantic_matrix_test = np.load(Path('/content/drive/MyDrive/semantic_similarity_matrix.npy'), mmap_mode=None, allow_pickle=True)
embeddings = np.load(Path('/content/drive/MyDrive/embeddings.npy'), mmap_mode=None, allow_pickle=True)
semantic_matrix = np.load(Path('/content/drive/MyDrive/semantic_matrix.npy'), mmap_mode=None, allow_pickle=True)

semantic_matrix.shape

semantic_matrix

semantic_matrix_test

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 10))
# Using a different color map (YlGnBu) helps distinguish the gradients
sns.heatmap(semantic_matrix, cmap="YlGnBu")
plt.title("Semantic Similarity Heatmap (AI Interpretation)")
plt.xlabel("Class Index")
plt.ylabel("Class Index")
plt.show()
plt.savefig("/content/drive/MyDrive/semantic_heatmap.png", dpi=300)

# # NOT NEEDED
# import numpy as np

# semantic_stretched = semantic_matrix.copy()

# off_diag_indices = np.where(~np.eye(semantic_matrix.shape[0], dtype=bool))
# off_diag_values = semantic_matrix[off_diag_indices]

# p_low = np.percentile(off_diag_values, 5)
# p_high = np.percentile(off_diag_values, 95)

# print(f"Stretching Blob: {p_low:.4f} -> {p_high:.4f}")

# semantic_stretched = (semantic_matrix - p_low) / (p_high - p_low)
# semantic_stretched = np.clip(semantic_stretched, 0, 1)

# np.fill_diagonal(semantic_stretched, 1.0)

semantic_matrix.shape

print(embeddings[0])

# semantic_stretched.shape

# semantic_matrix = semantic_stretched

"""**6. Construct the structural similarity matrix**"""

# scan the filtered .rsf dependency file from week 1 to construct a matrix where each entry is the number of packages each pair of files depend on.
# executing this cell produces 'struct_matrix_raw'
focused_rsf_path = Path("/content/drive/MyDrive/dsse_arcade_outputs/tika-focused.rsf")
class_to_index = {name: i for i, name in enumerate(cleaned_class_list)}
struct_matrix_raw = np.zeros((len(cleaned_class_list), len(cleaned_class_list)))
edges_mapped = 0

with open(focused_rsf_path, mode="r") as f:
    for line in f:
        rsf_contents = line.strip().split(" ")
        # print(src,dest)
        src, dest = rsf_contents[1].split('$')[0], rsf_contents[2].split('$')[0]
        if src in class_to_index and dest in class_to_index:
           i = class_to_index[src]
           j = class_to_index[dest]

           # Mark the connection
          #  print(f"connection: {src} to {dest}")
           struct_matrix_raw[i][j] = 1
           edges_mapped += 1
#np.fill_diagonal(struct_matrix_raw, 1.0) #THIS IS FOR SELF-SIMILARITY -- DONE LATER

edges_mapped

print(struct_matrix_raw)

struct_matrix_raw.shape

# import seaborn as sns
# import matplotlib.pyplot as plt

# plt.figure(figsize=(12, 10))
# sns.heatmap(struct_matrix_raw, cmap="Blues", cbar=False)
# plt.title("Structural Dependency Heatmap (Tika Core)")
# plt.xlabel("Target Class Index")
# plt.ylabel("Source Class Index")
# plt.show()

np.save(Path('/content/drive/MyDrive/struct_matrix_raw.npy'), struct_matrix_raw)

"""**7. Normalize the structural matrix**"""

max_overlap = struct_matrix_raw.max()
struct_matrix = struct_matrix_raw / max_overlap if max_overlap > 0 else struct_matrix_raw
np.fill_diagonal(struct_matrix, 1.0)

np.save(Path('/content/drive/MyDrive/struct_matrix.npy'), struct_matrix)

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 10))
sns.heatmap(struct_matrix, cmap="Blues", cbar=False)
plt.title("Structural Dependency Heatmap (Tika Core)")
plt.xlabel("Target Class Index")
plt.ylabel("Source Class Index")
plt.show()
plt.savefig("/content/drive/MyDrive/struct_heatmap.png", dpi=300)

"""**8. Combine the two matrices into one similarity matrix then apply complement.**"""

ALPHA = 0.4
combined_similarity = (ALPHA * struct_matrix) + ((1 - ALPHA) * semantic_matrix)

# Ensure similarity values are within [0, 1] before converting to distance
combined_similarity = np.clip(combined_similarity, 0.0, 1.0)

# Invert similarity to get distance
distance_matrix = 1.0 - combined_similarity
np.fill_diagonal(distance_matrix, 0)

semantic_matrix

struct_matrix

# USING 0 ALPHA
from scipy.cluster.hierarchy import dendrogram, linkage

Z = linkage(distance_matrix, method='complete')

plt.figure(figsize=(15, 7))
dendrogram(Z, labels=cleaned_class_list, leaf_rotation=90, leaf_font_size=8)
plt.title(f"Hierarchical Clustering Dendrogram (Alpha={ALPHA})")
plt.xlabel("Class Name")
plt.ylabel("Distance")
plt.show()

# USING 1 ALPHA
from scipy.cluster.hierarchy import dendrogram, linkage

Z = linkage(distance_matrix, method='complete')

plt.figure(figsize=(15, 7))
dendrogram(Z, labels=cleaned_class_list, leaf_rotation=90, leaf_font_size=8)
plt.title(f"Hierarchical Clustering Dendrogram (Alpha={ALPHA})")
plt.xlabel("Class Name")
plt.ylabel("Distance")
plt.show()

# USING 0.4 ALPHA
from scipy.cluster.hierarchy import dendrogram, linkage

Z = linkage(distance_matrix, method='complete')

plt.figure(figsize=(15, 7))
dendrogram(Z, labels=cleaned_class_list, leaf_rotation=90, leaf_font_size=8)
plt.title(f"Hierarchical Clustering Dendrogram (Alpha={ALPHA})")
plt.xlabel("Class Name")
plt.ylabel("Distance")
plt.show()
plt.savefig("/content/drive/MyDrive/arc_clustering_dendogram.png", dpi=300)

"""**9. Apply clustering**"""

# Silhouette_score for optimal number of clusters between 0 and 20
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import silhouette_score
import numpy as np

# 1. Define the sensible range of clusters for a 64-class system
min_clusters = 5
max_clusters = 20

best_score = -1.0
best_k = 10
scores = []

print("Evaluating cluster counts (k)...")

# 2. Test every possible cluster count
for k in range(min_clusters, max_clusters + 1):
    # Run the clustering for this 'k'
    clusterer = AgglomerativeClustering(n_clusters=k, metric='precomputed', linkage='complete')
    temp_labels = clusterer.fit_predict(distance_matrix)

    # Calculate the mathematical quality of these clusters
    # Note: We must pass metric='precomputed' to the scorer as well
    score = silhouette_score(distance_matrix, temp_labels, metric='precomputed')
    scores.append(score)

    print(f"k={k}: Silhouette Score = {score:.4f}")

    # Save the best one
    if score > best_score:
        best_score = score
        best_k = k

# 3. Apply the mathematically proven optimum
print(f"OPTIMAL CLUSTER COUNT FOUND: {best_k} (Score: {best_score:.4f})")

TARGET_NUM_CLUSTERS = best_k

# 4. Generate your final, optimal ARC clusters
final_clusterer = AgglomerativeClustering(n_clusters=TARGET_NUM_CLUSTERS, metric='precomputed', linkage='complete')
clusters = final_clusterer.fit_predict(distance_matrix)

TARGET_NUM_CLUSTERS = 16 # how such parameter could be optimized?
clusterer = AgglomerativeClustering(n_clusters=TARGET_NUM_CLUSTERS, metric='precomputed', linkage='complete') # what is 'precomputed' & 'linkage'?
clusters = clusterer.fit_predict(distance_matrix)

arc_output_path = "/content/drive/MyDrive/tika-arc.rsf"

# Write the cluster mappings to the RSF file
with open(arc_output_path, "w") as f:
    for idx, class_name in enumerate(cleaned_class_list):
        cluster_id = clusters[idx]

        # Format explicitly required for Week 4:
        # contain Cluster_X org.apache.tika.parser.Parser
        f.write(f"contain Cluster_{cluster_id} {class_name}\n")

print(f"Success! Optimal ARC clusters saved to: {arc_output_path}")

print("\n--- Output Preview ---")
with open(arc_output_path, "r") as f:
    for _ in range(5):
        print(f.readline().strip())

import pandas as pd

# Create a summary table
cluster_summary = pd.Series(clusters).value_counts().sort_index().reset_index()
cluster_summary.columns = ['Cluster ID', 'File Count']
cluster_summary['Percentage'] = (cluster_summary['File Count'] / len(clusters)) * 100

print(cluster_summary.to_string(index=False))

clusters

"""**10. Visulizations**"""

# According to the applied algorithm documentation, provide any visualizations for better understanding of how the clusters are formed.

